language: python
dist: xenial
os:
  - linux
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"
env:
  global:
    - secure: hITh6brp/zNPcjnQ1bu+Q46c/27u28xd9jrMjz9RKvbXIromQp4reI8Zok608zSvL8l3MKf34OKp2vii7nb7//cg1Tk+aBeI0YJE+pe0Hb3u/NchCFGZ9geTpi1sR7ylHcehwiamzcW2KODS4mEnXGP8FIiV2lPdomIh0Xqo96a9fvqXvBkM437llTMvwaVCA015+X3yWseod7Wwph55sqKYJfu7DhPGs7lUZzh14WxPVpb98U22SrcMfIOEmoTwPZfI8RYW2MQyH684DT++CCGN7tMY3oEgTSnFseEoV9Tc2ZAdH5Y2FG1oB51yIOZwkLCWfWfcdm7bdqUIMsbyV2OX1QfkEBYv6zeQMFyr7aeaC4sJIG0/4+OL4T4Wy3MEQ8JeQtfbVMxzSgT2jnM5pa84wii02Trb95eC9tF3f/NolyrPc/U1D4gveCKTWFSkXUjuCMsw73xDAkxnnb44xfKCDr/eqyEtRrujZso0cyR5pCc62A/A/yAsYPQ4z2yLXlazBCDo5OHU9T1nWFUG7WqEYvOSzh8Eu5ekvhjHc8RDiMwzNCGxmYg1PAG6oDLfJMTS41SfwTLPx6TO45/RyMldkQc8IAY9BYtIHOyOrCaJtBdH9TDT1Bh1r+83IhVJn+P+jCXlamG+/AFebF+uQZJc/oAy6KrWFiQwqS35O34=
before_install:
  - pip install poetry
install:
  - poetry install
script:
  - poetry run black --check .
  - poetry run flake8
  - poetry run pytest -vvvx --cov=monitorcontrol tests/
  - poetry run sphinx-build -W -b html docs public
after_success:
  - poetry run coveralls
before_deploy:
  - poetry config pypi-token.pypi $PYPI_TOKEN
deploy:
  provider: script
  script: poetry publish --build
  cleanup: false
  on:
    tags: true
    all_branches: true
    condition: $TRAVIS_PYTHON_VERSION == 3.8
